version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: new_job_platform
      MYSQL_USER: root
      MYSQL_PASSWORD: sa

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: sa
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    networks:
      - mysql_network
    restart: unless-stopped

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
